# Site settings

title: Wingo Lab
#email: wingolab@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  A genetics laboratory dedicated to finding and fighting the causes of
  Alzheimer's disease at the Atlanta Veterans Administration and Emory
  University's Center for Neurodegenerative Disease.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wingolab.org" # the base hostname & protocol for your site

#twitter_username: wingolab
github_username: wingolab
gaaccount: ''

# Build settings
permalink: /:year/:month/:title
paginate: 3
#highligher: pygments
markdown: kramdown
theme: minima

sass:
  sass_dir: _scss

exclude:
- README.md
- LICENSE
- sgeOnHgcc.md

lab_members:
  - category: "Principal Investigators"
    people:
      - pic_name: Aliza
        links:
          - href: "https://www.ncbi.nlm.nih.gov/pubmed/?term=wingo+a%3F%5Bauthor%5D+or+wingo+ap%5Bauthor%5D"
            name: "PubMed"
        description: Dr. Wingo is an Assistant Professor of Psychiatry at Emory University and board-certified psychiatrist. She received her medical degree and residency training at Emory University School of Medicine. Subsequently, she completed a research fellowship, Master of Science in Clinical Research, and career development award under the mentorship of Kerry Ressler, MD, Ph.D. Dr. Wingo studies the genetic and molecular basis of depression, PTSD, as well as of psychological resilience and well-being. Additionally, Dr. Wingo investigates molecular mechanisms underlying the detrimental and protective effects of psychological factors on dementia risk. As an early-stage investigator, Dr. Wingo has received an American Psychiatric Association/Lilly Resident Research award, American Psychiatric Association Research Fellowship award, a NARSAD Young Investigator award, a VA Career Development Award, and recently three federal grants (R01, U01, Merit) to pursue her lines of research inquiries.
        title: Aliza P. Wingo, M.D., M.S.
      - pic_name: Thomas
        links:
          - href: "https://www.ncbi.nlm.nih.gov/myncbi/thomas.wingo.1/bibliography/public/"
            name: "NCBI Bibliography"
          - href: "https://www.ncbi.nlm.nih.gov/pubmed/?term=wingo+ts%5Bauthor%5D+or+wingo+t%3F%5Bauthor%5D"
            name: "PubMed"
          - href: "https://scholar.google.com/citations?user=kJYqCEsAAAAJ&hl=en&oi=ao"
            name: "Google Scholar"
          - href: "https://github.com/wingolab/"
            name: "GitHub"
        description: Dr. Wingo is an Associate Professor of Neurology and Human Genetics at Emory University. His primary lab is at the Center for Neurodegenerative Disease in the Whitehead building on Emory’s main campus. He has post-doctoral training in statistical genetics, next-generation sequencing, and bioinformatics. He is a board certified neurologist with fellowship training in cognitive neurology. Dr. Wingo is a member of the Population Biology Evolution and Ecology Graduate Program at Emory University.
        title: Thomas S. Wingo, M.D.
  - category: "Research Staff"
    people:
      - pic_name: Adriana
        description: Dr. Lori received her Ph.D. in Genetic Sciences at the University of Pisa (Italy). Her dissertation focused on identifying chromosomal damages in children exposed to Chernobyl fallout to estimate long-term effects of radiation to the genome. Dr. Lori’s current research involves the role of genetic and epigenetic mechanisms in the development of stress-related disorders and social behaviors. Dr. Lori has been one of the primary genetic investigators of the Grady Trauma Project involved in molecular and bioinformatics analyses of sequence variants, GWAS and whole genome sequencing. Dr. Lori joined the Wingo lab in 2018 as a Research Associate.
        title: Adriana Lori, Ph.D.
      - pic_name: Ekaterina
        description: Dr. Gerasimov earned her doctoral degree in computer science at Georgia State University. She has comprehensive experience in bioinformatics and computational genomics and algorithms. Her general research interest at GSU was designing and applying advanced algorithms and statistical tools for analysis of next-generation sequencing data related to cancer and infection diseases. Dr. Gerasimov joined the Wingo lab in 2018 as an Assistant Bioinformatics Scientist.
        title: Ekaterina Gerasimov, Ph.D.
      - pic_name: Jacob        
        description: Jacob Meigs received his B.E. in Computer Engineering from the University of South Carolina. His diverse experience extends into web development, software development, and independent web consulting. He joined the Wingo lab in March 2019 and assists in developing and maintaining the lab’s web applications and contributing to the development of tools for general analysis.
        title: Jacob Meigs, B.E.
      - pic_name: Leo
        description: Leo Zhao received his B.S. in Biology and Music from Emory University. As an undergraduate student, he studied the role of PTPN21 in cell mechanical properties of hematopoietic stem cells, its role in HSCs niche retention and function, as well as its role in leukemogenesis. Leo joined the Wingo lab in 2019 as a Research Specialist.
        title: Leo Zhao, B.S.
      - pic_name: Minnie
        description: Se Min (Minnie) Canon is the Wingo Lab Manager and Senior Research Specialist. She first joined the Wingo Lab as an Undergraduate Research Assistant in Fall of 2012 while attending Emory College. During this time, she did a Senior Research Project on identifying genetic causes of an early-onset Alzheimer’s disease case in a family cohort from Colombia. After graduating with a Bachelor of Science (B.S.) in Neuroscience and Behavioral Biology from Emory University, she joined the lab full-time in 2014. Her work primarily involves nucleic acid extraction and quantification, DNA and miRNA library preparation for sequencing, and DNA genotyping and gene expressions. She manages and oversees research experiments and quality control.
        title: Se Min (Minnie) Canon, B.S.
      - pic_name: Yue
        description: Dr. Yue Liu obtained his Ph.D from Structural and Computational Biology and Molecular Biophysics program at Baylor College of Medicine (BCM). His thesis work was in assembling whole genome sequencing data for complex genomes at the Human Genome Sequencing Center (HGSC) at BCM. He has since worked at HGSC for various projects in next generation sequencing data analysis. His current interest and focus at Wingo’s lab is to combine proteomics and sequencing data for better understanding of the abundance profile of the proteins and its association to diseases.
        title: Yue Liu, Ph.D.
  - category: "Post-Doctoral Fellows"
    people:    
      - pic_name: Chloe
        description: Dr. Robins received her Ph.D. from the Population Biology, Ecology, and Evolution Graduate Program at Emory University. Her doctoral work used statistical genetic methods to investigate the evolutionary basis of human aging. She joined the Wingo Lab after graduation, and is now working on identifying epigenetic and proteomic changes associated with Alzheimer’s Disease.
        title: Chloe Robins, Ph.D.
  - category: "Graduate Students"
    people:
      - pic_name: Felicia
        description: Felicia Obialo is from Atlanta, GA. She obtained her undergraduate degree in psychology from Xavier University of Louisiana, her master’s degree in neuroscience from Tulane University, and is currently a 4th year medical student at University of North Carolina at Chapel Hill with plans to practice holistic psychiatry.
        title: Felicia Obialo, B.S.
      - description: Huige Jiang graduated from Georgia Tech with a B.S. in Biomedical Engineering and is currently pursuing a MSPH degree in Biostatistics. She started working in the Wingo lab in May 2019. Her current project is to simulate TMT proteomics data and test the performance of 2 quality control pipelines.
        title: Huige Jiang, B.S.
      - pic_name: Nadia
        description: Nadia Harerimana is from Kigali, Rwanda and received her B.A degree in Human Ecology from College of the Atlantic. She is a current graduate student in Genetics and Molecular Biology program at Emory University. Her predoctoral training in the Wingo lab focuses on integrating different types of omics data and using statistical tools to illuminate the shared genetic and molecular risk factors that contribute to depression and AD dementia
        title: Nadia Harerimana
      - pic_name: Mei
        description: Mei Zhen is a graduate student in 8-year Clinical Medicine program from Xiangya School of Medicine, Central South University. Her work is mainly focused on the association between miRNAs and cognitive trajectory.
        title: Mei Zhen
  - category: "Undergraduate Students"
    people:      
      - pic_name: Mikolaj
        description: Mikolaj Figurski is an undergraduate student at Emory University, aiming to graduate in 2022 with a Computer Science B.S and an Economics B.A. He joined the Wingo Lab in October 2018 as a Data Science / Software Development intern, and now actively supports the lab's web application development team.
        title: Mikolaj Figurski